spring:
  application:
    name: processor_stream
  cloud:
    stream:
      bindings:
        input:
          destination: source
          contentType: text/plain
        output:
          destination: sink
          contentType: text/plain
      kafka:
        brokers: localhost
        defaultBrokerPort: 9092